### ISSUE TITLE
Operator projects using the removed APIs in k8s 1.22 requires changes

### ISSUE THREAD

**Issue by camilamacedo86** [armory/spinnaker-operator#245] opened 2021-09-01 22:37 UTC
Based on the comment. It should be here: https://github.com/spinnaker/spinnaker/issues/6520#issuecomment-910729798
### Problem Description

Kubernetes has been deprecating API(s), which will be removed and are no longer available in 1.22. Operators projects using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) versions will **not** work on Kubernetes 1.22 or any cluster vendor using this Kubernetes version(1.22), such as OpenShift 4.9+. Following the APIs that are most likely your projects to be affected by:
- apiextensions.k8s.io/v1beta1: (Used for CRDs and available since v1.16)
- rbac.authorization.k8s.io/v1beta1: (Used for RBAC/rules and available since v1.8)
- admissionregistration.k8s.io/v1beta1 (Used for Webhooks and available since v1.16)

Therefore, looks like this project distributes solutions in the [repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/spinnaker-operator) and does not contain any version compatible with k8s 1.22/OCP 4.9. ([More info](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138)). Following some findings by checking the distributions published:

- **spinnaker-operator.v1.21.2**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["spinnakeroperators.charts.helm.k8s.io"]) 
- **spinnaker-operator.v1.13.1**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["spinnakeroperators.charts.helm.k8s.io"]) 
- **spinnaker-operator.v1.17.2**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["spinnakeroperators.charts.helm.k8s.io"]) 
- **spinnaker-operator.v1.17.4**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["spinnakeroperators.charts.helm.k8s.io"]) 
- **spinnaker-operator.v1.20.3**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["spinnakeroperators.charts.helm.k8s.io"]) 

**NOTE:** The above findings are only about the manifests shipped inside of the distribution. It is not checking the codebase.

### How to solve

It would be very nice to see new distributions of this project that are no longer using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) and so they can work on Kubernetes 1.22 and newer and published in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/spinnaker-operator) collection. OpenShift 4.9, for example, will not ship operators anymore that do still use v1beta1 extension APIs.

Due to the number of options available to build Operators, it is hard to provide direct guidance on updating your operator to support Kubernetes 1.22. Recent versions of the [OperatorSDK](https://github.com/operator-framework/operator-sdk) greater than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) and [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) greater than [3.0.0](https://github.com/kubernetes-sigs/kubebuilder/releases) scaffold your project with the latest versions of these APIs (all that is generated by tools only). See the guides to upgrade your projects with OperatorSDK [Golang](https://sdk.operatorframework.io/docs/building-operators/golang/migration/), [Ansible](https://sdk.operatorframework.io/docs/building-operators/ansible/migration/), [Helm](https://sdk.operatorframework.io/docs/building-operators/helm/migration/) or the [Kubebuilder](https://book.kubebuilder.io/migration/v2vsv3.html) one. For APIs other than the ones mentioned above, you will have to check your code for usage of removed API versions and upgrade to newer APIs. The details of this depend on your codebase.

**If this projects only need to migrate the API for CRDs and it was built with [OperatorSDK](https://github.com/operator-framework/operator-sdk) versions lower than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) then, you maybe able to solve it with an [OperatorSDK](https://github.com/operator-framework/operator-sdk) version >= v0.18.x < 1.0.0:**

> $ operator-sdk generate crds --crd-version=v1
> INFO[0000] Running CRD generator.                       
> INFO[0000] CRD generation complete.

**Alternatively, you can try to upgrade your manifests with [controller-gen](https://book.kubebuilder.io/reference/controller-gen.html) ([version >= v0.4.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.1)) :**

#### If this project does not use Webhooks:

> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role  paths="./..."

#### If this project is using Webhooks:

1. Add the markers [sideEffects](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L81) and [admissionReviewVersions](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L114) to your webhook (Example with sideEffects=None and admissionReviewVersions={v1,v1beta1}: [memcached-operator/api/v1alpha1/memcached_webhook.go](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go#L39)):

2. Run the command:
> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths="./..."

For further information and tips see the [comment](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138#discussioncomment-1245759).

**Comment by pwamej** [comment] 2022-01-25 18:16
Bumping this up.

**Comment by ichi0915** [comment] 2022-03-21 23:41
Hi, I have also updated the CRD and i'm getting the same error as [mtaylor98](https://github.com/mtaylor98), I think it is related to the go client the operator uses.

I'll trying to update the dependencies to see if that solves the issue.

**Comment by CB-GuangyaoXie** [comment] 2022-04-07 23:29
Bumping this up.

**Comment by ArtemChekunov** [comment] 2022-04-13 09:40
Bumping this up.

**Comment by CB-GuangyaoXie** [comment] 2022-04-13 17:17
> Hi, I have also updated the CRD and i'm getting the same error as [mtaylor98](https://github.com/mtaylor98), I think it is related to the go client the operator uses.
> 
> I'll trying to update the dependencies to see if that solves the issue.

@ichi0915 Hi, any luck with updating the dependencies?

**Comment by ichi0915** [comment] 2022-04-14 00:24
Hi, this is everything I've done so far [ichi0915/spinnaker-operator](https://github.com/ichi0915/spinnaker-operator/commits/master)

Basically I updated the CRDs, the dependencies, the code and the dockerfile.

With this changes I'm able to install the operator in k8s v1.22 without any issue, but when I try to apply the [kustomize patches](https://github.com/ichi0915/spinnaker-kustomize-patches-oss) the spinnaker-operator is giving me a similar error as [This issue](https://github.com/armory/spinnaker-operator/issues/251) in my case the error is the following:

```bash
SpinnakerService validation failed:
	Unable to read spinnaker version from manifest:
	Unable to read property \"version\":
	invalid interface found at version
```

I'm currently debugin that, but I think the cause has something to do with the function that parses the yaml, and also I saw that [seanrclayton](https://github.com/armory/spinnaker-operator/pull/250/files) has different CRD's than me I'll try with his CRD's to see if it works.

**Comment by ichi0915** [comment] 2022-04-15 21:55
Hi, yesterday I did some more changes to de CRD's, I added the flags `x-kubernetes-preserve-unknown-fields: true` to some fields and now when I apply the kustomize patches the operator parser saves those values and does the deployment succesfully, here is a [PR](https://github.com/armory/spinnaker-operator/pull/252) with all the changes, I'll still need do some test to verify everything is fine.

**Comment by ArtemChekunov** [comment] 2022-05-02 14:39
Hi @ichi0915,

how is your test?

**Comment by andrijaperovic** [comment] 2022-06-15 22:10
Any idea on which version of the Spinnaker Operator v1.22 will be supported?
Or is the recommended approach still to update the CRDs, the dependencies, the code and the Dockerfile as @ichi0915 is suggesting?

**Comment by gnanderson** [comment] 2022-06-22 10:11
@andrijaperovic We kicked the tyres on this internally and decided we had no bandwidth to help maintain this operator, mostly because it looks like it's not been updated to recent Operator SDK versions in quite a while and there's *a lot* of work to bring it up to date.

For us at least, this operator was probably the only thing keeping Spinnaker in use on our clusters and our team are now rolling out and migrating to an alternative.

**Comment by mtaylor98** [comment] 2022-07-11 16:22
I have started using the updated Halyard and Operator images as well as the updated CRDs which does allow me to deploy the operator and such properly. However, I am now running into an issue where secrets do not work in the SpinnakerService yaml at all. Whether they be specified in the profiles: section or main config section, if they take the format in the documentation as:

```encryptedFile:k8s!``` or as ```encrypted:k8s!``` I get an error when the services deploy that say:

```Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.                                                                                                             │
│ 2022-07-11 14:38:22.165 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :                                                                                                                              │
│                                                                                                                                                                                                                               │
│ ***************************                                                                                                                                                                                                   │
│ APPLICATION FAILED TO START                                                                                                                                                                                                   │
│ ***************************                                                                                                                                                                                                   │
│                                                                                                                                                                                                                               │
│ Description:                                                                                                                                                                                                                  │
│                                                                                                                                                                                                                               │
│ Failed to bind properties under 'sql.connectionpools.default.password' to java.lang.String:                                                                                                                                   │
│                                                                                                                                                                                                                               │
│     Reason: Secret Engine does not exist: k8s                                                                                                                                                                                 │
│                                                                                                                                                                                                                               │
│ Action:                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                               │
│ Update your application's configuration```

**Comment by rscottwatson** [comment] 2022-07-11 20:22
@mtaylor98 we had this error too and we were told that we needed to use S3 as a secret store as k8s was not supported in the oss version of the operator despite this https://github.com/armory/spinnaker-operator/blob/master/doc/managing-spinnaker.md#secrets-in-kubernetes-secrets suggesting that k8s was a valid secret engine.

**Comment by andrijaperovic** [comment] 2022-07-11 20:23
> I have started using the updated Halyard and Operator images as well as the updated CRDs which does allow me to deploy the operator and such properly. However, I am now running into an issue where secrets do not work in the SpinnakerService yaml at all. Whether they be specified in the profiles: section or main config section, if they take the format in the documentation as:
> 
> `encryptedFile:k8s!` or as `encrypted:k8s!` I get an error when the services deploy that say:
> 
> ```
> │ 2022-07-11 14:38:22.165 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :                                                                                                                              │
> │                                                                                                                                                                                                                               │
> │ ***************************                                                                                                                                                                                                   │
> │ APPLICATION FAILED TO START                                                                                                                                                                                                   │
> │ ***************************                                                                                                                                                                                                   │
> │                                                                                                                                                                                                                               │
> │ Description:                                                                                                                                                                                                                  │
> │                                                                                                                                                                                                                               │
> │ Failed to bind properties under 'sql.connectionpools.default.password' to java.lang.String:                                                                                                                                   │
> │                                                                                                                                                                                                                               │
> │     Reason: Secret Engine does not exist: k8s                                                                                                                                                                                 │
> │                                                                                                                                                                                                                               │
> │ Action:                                                                                                                                                                                                                       │
> │                                                                                                                                                                                                                               │
> │ Update your application's configuration```
> ```

@mtaylor98 this is the expected behavior I believe - k8s secret engine is only available with armory operator (https://github.com/armory-io/spinnaker-operator), not the OSS operator & spinnaker.

The only supported secret engines for OSS are GCS/S3:
https://spinnaker.io/docs/reference/halyard/secrets/#supported-secret-engines

**Comment by kalyano** [comment] 2022-07-11 21:12
> @mtaylor98 we had this error too and we were told that we needed to use S3 as a secret store as k8s was not supported in the oss version of the operator despite this https://github.com/armory/spinnaker-operator/blob/master/doc/managing-spinnaker.md#secrets-in-kubernetes-secrets suggesting that k8s was a valid secret engine.

Hi Scott,
Can I ask who had recommended you to use S3 vs K8s secret engine? Was this someone from the armory team?
I need to dig into why we mentioned K8s secrets on the link you posted; and if required, we will need to change/remove K8s secrets from here.

**Comment by mtaylor98** [comment] 2022-07-12 13:26
@kalyano @rscottwatson @andrijaperovic 

I am surprised to hear this. Prior to Kubernetes v1.22 I was using Kubernetes Secrets with the OSS operator and Spinnaker with no issue at all. It is only since the updates that this has been unsupported for me and that I have run into any issues. I was using my identical SpinnakerService yaml file and everything from prior to the changes in the upgrades. The docs even point out that Kubernetes Secrets is supported:

https://github.com/armory/spinnaker-operator#benefits-of-operator

```Store Spinnaker secrets in Kubernetes secrets.```

**Comment by carlos4ndre** [comment] 2023-01-28 11:20
any updates on this? estimates to when a fix will be released with an upgrade path to follow?

**Comment by sergio-quintero** [comment] 2023-03-02 23:11
Hi all - [Latest Operator 1.3.0 release](https://github.com/armory/spinnaker-operator/releases/tag/v1.3.0) has added support for K8s 1.22+. 

[K8s Compatibility Matrix](https://github.com/armory/spinnaker-operator#kubernetes-compatibility-matrix)

**Closed** 2023-03-24 23:23 UTC
